// <auto-generated />
namespace CodeTheWay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class VolunteerDonor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VolunteerDonor));
        
        string IMigrationMetadata.Id
        {
            get { return "201911140253513_VolunteerDonor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
